services:
  cp:
    build:
      context: .
      dockerfile: Dockerfile.cp
    ports:
      - "8080:8080"
    env_file: .env.local
    environment:
      AAS_ROLE: control-plane
    networks:
      - aas

  worker-1:
    build:
      context: .
      dockerfile: Dockerfile.worker
    env_file: .env.local
    environment:
      AAS_ROLE: worker
    networks:
      - aas

  worker-2:
    build:
      context: .
      dockerfile: Dockerfile.worker
    env_file: .env.local
    environment:
      AAS_ROLE: worker
    networks:
      - aas

  worker-3:
    build:
      context: .
      dockerfile: Dockerfile.worker
    env_file: .env.local
    environment:
      AAS_ROLE: worker
    networks:
      - aas

networks:
  aas:
